---
apiVersion: v1
kind: Service
metadata:
  name: gopi-mlb
  labels:
    app: polls-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: polls-app
    tier: frontend
